# Generated by Django 5.2.6 on 2025-09-24 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uid', models.UUIDField()),
                ('detail_code', models.CharField(blank=True, max_length=64, null=True)),
                ('before_value', models.TextField(blank=True, null=True)),
                ('after_value', models.TextField(blank=True, null=True)),
                ('actor', models.CharField(max_length=128)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EntityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uid', models.UUIDField(db_index=True)),
                ('detail_code', models.CharField(max_length=64)),
                ('detail_value', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('hashdiff', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_uid', 'detail_code', 'is_current'], name='crm_entityd_entity__0df034_idx'), models.Index(fields=['valid_from'], name='crm_entityd_valid_f_9cbf38_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('entity_uid', 'detail_code'), name='uniq_entity_detail_current')],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('display_name', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('hashdiff', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.entitytype')),
            ],
            options={
                'indexes': [models.Index(fields=['entity_uid', 'is_current'], name='crm_entity_entity__80df0c_idx'), models.Index(fields=['valid_from'], name='crm_entity_valid_f_071d02_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('entity_uid',), name='uniq_entity_current')],
            },
        ),
    ]
